name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.7.2
  animations: ^2.0.5
  chewie: ^1.7.0   # for fullscreen playback
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0  # Updated version
  lottie: ^2.2.0
  firebase_core: 3.13.0
  firebase_database: ^11.3.5
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  flutter_secure_storage: ^5.0.2
  supabase_flutter: ^1.10.25
  timeago: ^3.6.0
  image_picker: ^0.8.9
  path: ^1.8.3
  mime: ^1.0.4
  http: ^1.4.0
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  image_picker: ^0.8.7+4


flutter:
  uses-material-design: true

  assets:
    - assets/images/football_action.jpg
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/5.jpeg
    - assets/images/dali.jpeg
    - assets/images/cr7.jpeg
    - assets/images/mb.jpeg
    - assets/images/goat.png
    - assets/images/football_field.jpeg
    - assets/images/club_logo.jpeg
    - assets/images/player1.jpeg
    - assets/images/scout.jpeg
    - assets/images/6.jpeg
    - assets/images/7.jpeg
    - assets/images/8.jpeg
    - assets/images/9.jpeg
    - assets/images/10.jpeg
    - assets/images/11.jpeg
    - assets/images/12.jpeg
    - assets/images/13.jpeg
    - assets/images/14.jpeg  
    - assets/images/logo.png
    - assets/images/gold_foil_texture.png
    - assets/images/club_logo.jpeg
    - assets/images/player2.jpeg
    - assets/images/player3.jpeg
    - assets/images/player4.jpeg
    - assets/images/player5.jpeg
    - assets/images/player6.jpeg
    - assets/images/player7.jpeg
    - assets/images/player_avatar.jpeg
    - assets/images/player_avatar1.jpeg
    - assets/images/scout_badge.png
    - assets/videos/football.mp4
    - assets/videos/goal1.mp4
    - assets/videos/goal2.mp4
    - assets/videos/goal3.mp4
    - assets/audio/