// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgEjlf_4YNQtwmQgv_HGLRsywhaE0sdT4',
    appId: '1:914193261613:web:d2e92a5b64649253da84a4',
    messagingSenderId: '914193261613',
    projectId: 'el-goat-68dc8',
    authDomain: 'el-goat-68dc8.firebaseapp.com',
    storageBucket: 'el-goat-68dc8.firebasestorage.app',
    measurementId: 'G-W3T3YFQB2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_6btH9fYLh05UvwZ1E57vymSCADGuWIc',
    appId: '1:914193261613:android:e36fb7d41bb846c7da84a4',
    messagingSenderId: '914193261613',
    projectId: 'el-goat-68dc8',
    storageBucket: 'el-goat-68dc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmuc4iVrRwFUAeq_JXJk4JDjmB9Vuf9fU',
    appId: '1:914193261613:ios:f456977b7cd20487da84a4',
    messagingSenderId: '914193261613',
    projectId: 'el-goat-68dc8',
    storageBucket: 'el-goat-68dc8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmuc4iVrRwFUAeq_JXJk4JDjmB9Vuf9fU',
    appId: '1:914193261613:ios:f456977b7cd20487da84a4',
    messagingSenderId: '914193261613',
    projectId: 'el-goat-68dc8',
    storageBucket: 'el-goat-68dc8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgEjlf_4YNQtwmQgv_HGLRsywhaE0sdT4',
    appId: '1:914193261613:web:cf64e29cbf760316da84a4',
    messagingSenderId: '914193261613',
    projectId: 'el-goat-68dc8',
    authDomain: 'el-goat-68dc8.firebaseapp.com',
    storageBucket: 'el-goat-68dc8.firebasestorage.app',
    measurementId: 'G-KRT23BT5QL',
  );
}
