name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.19
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0  # Updated version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/football_action.jpg
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/5.jpeg
    - assets/images/dali.jpeg
    - assets/images/cr7.jpeg
    - assets/images/mb.jpeg
    - assets/images/goat.png
    - assets/videos/football.mp4